-- tests/smoke.lua -- Smoke headless test for P10
-- Verifica love . --test sin ventana, 0.5s, sin errores
package.path = "../?.lua;../?/init.lua;./?.lua;./tests/?.lua;" .. package.path
local harness = require("tests.test_harness")
local world = require("core.world")
local shop = require("systems.shop")
local persistence = require("systems.persistence")
local timers = require("core.timers")
local events = require("core.events")

harness.describe("Smoke: Headless Core Load", function()
    harness.it("loads core modules without errors", function()
        harness.assert_not_nil(world, "world must load")
        harness.assert_not_nil(shop, "shop must load")
        harness.assert_not_nil(persistence, "persistence must load")
        harness.assert_not_nil(timers, "timers must load")
        harness.assert_not_nil(events, "events must load")
    end)
    harness.it("world reset and shop reset do not throw", function()
        local ok, err = pcall(function()
            world.reset()
            shop.reset()
            timers.clear()
            events.clear()
        end)
        harness.assert_true(ok, "reset must not throw: " .. tostring(err))
    end)
    harness.it("love filesystem smoke", function()
        local ok = pcall(function() love.filesystem.__clearVFS() end)
        harness.assert_true(ok, "VFS clear must not throw")
    end)
end)
