local harness = require("tests.test_harness")
local persistence = require("systems.persistence")
local shrine = require("systems.shrine")
local shrineShop = require("systems.shrineShop")
local defs = require("systems.shrineDefs")
local world = require("core.world")
local function reset_env()
    love.filesystem.__clearVFS()
    persistence.profilesData = {version = 3, schema_version = 3, activeProfileIndex = nil, profiles = {}}
    persistence.createProfile("ShrineHero")
    world.state.monedas = 0
    world.state.highScore = 0
    world.state.highestStreak = 1.0
    world.state.ironBodyUsed = false
end
harness.describe("Shrine: datos y billetera", function()
    harness.before_each(reset_env)
    harness.it("perfil nuevo trae shrineCoins en 0 y 8 talentos en 0", function()
        local p = persistence.getActiveProfile()
        harness.assert_equal(0, p.shrineCoins, "shrineCoins inicia en 0")
        harness.assert_equal(0, shrine.rank("heritage_pouch"), "talento inicia en 0")
        harness.assert_equal(8, #defs.LIST, "8 talentos definidos")
    end)
    harness.it("compra descuenta shrineCoins y sube rango sin tocar monedas", function()
        local p = persistence.getActiveProfile()
        p.shrineCoins = 500
        p.monedas = 77
        local ok, _, price = shrineShop.buy("heritage_pouch")
        harness.assert_true(ok, "compra rango 1 exitosa")
        harness.assert_equal(100, price, "precio heritage 1 = 100")
        harness.assert_equal(400, p.shrineCoins, "descuenta billetera")
        harness.assert_equal(77, p.monedas, "monedas intactas")
        harness.assert_equal(1, shrine.rank("heritage_pouch"), "rango sube a 1")
    end)
    harness.it("rechaza sin fondos y en rango maximo", function()
        local p = persistence.getActiveProfile()
        p.shrineCoins = 10
        local ok, err = shrineShop.buy("iron_body")
        harness.assert_false(ok, "sin fondos rechaza")
        harness.assert_not_nil(err, "mensaje de error")
        p.shrineCoins = 9999
        shrineShop.buy("mercy_pact")
        shrineShop.buy("mercy_pact")
        local ok3 = shrineShop.buy("mercy_pact")
        harness.assert_false(ok3, "rango maximo rechaza")
    end)
    harness.it("cierre de run acredita 20% a shrineCoins", function()
        local p = persistence.getActiveProfile()
        p.monedas = 100
        persistence.saveProfiles()
        local earned = persistence.closeRunToShrine()
        harness.assert_equal(20, earned, "acredita 20")
        harness.assert_equal(20, p.shrineCoins, "billetera suma 20")
        harness.assert_equal(80, p.monedas, "run conserva 80")
    end)
end)
harness.describe("Shrine: efectos", function()
    harness.before_each(reset_env)
    harness.it("heritage otorga 0/5/10/15", function()
        harness.assert_equal(0, shrine.heritageCoins(), "sin rango = 0")
        local p = persistence.getActiveProfile()
        p.shrineCoins = 9999
        shrineShop.buy("heritage_pouch")
        shrineShop.buy("heritage_pouch")
        harness.assert_equal(10, shrine.heritageCoins(), "rango 2 = 10")
    end)
    harness.it("revive cuesta 30/25/20", function()
        harness.assert_equal(30, shrine.reviveCost(), "base 30")
        local p = persistence.getActiveProfile()
        p.shrineCoins = 9999
        shrineShop.buy("mercy_pact")
        harness.assert_equal(25, shrine.reviveCost(), "rango 1 = 25")
        shrineShop.buy("mercy_pact")
        harness.assert_equal(20, shrine.reviveCost(), "rango 2 = 20")
    end)
    harness.it("comboWindow es maximo entre tarot y foco", function()
        local base = shrine.comboWindow()
        harness.assert_true(base >= 8.0, "base >= 8.0")
        local p = persistence.getActiveProfile()
        p.shrineCoins = 9999
        shrineShop.buy("hunter_focus")
        shrineShop.buy("hunter_focus")
        harness.assert_true(shrine.comboWindow() >= 10.0, "rango 2 >= 10.0")
    end)
    harness.it("iron body perdona una vez por etapa", function()
        local p = persistence.getActiveProfile()
        p.shrineCoins = 9999
        harness.assert_false(shrine.consumeIronBody(world.state), "sin rango no perdona")
        shrineShop.buy("iron_body")
        world.state.ironBodyUsed = false
        harness.assert_true(shrine.consumeIronBody(world.state), "primera vez perdona")
        harness.assert_false(shrine.consumeIronBody(world.state), "segunda vez no")
    end)
    harness.it("dragon alarga duraciones y magnet base es el rango", function()
        harness.assert_equal(0, shrine.magnetBase(), "magnet base 0")
        local p = persistence.getActiveProfile()
        p.shrineCoins = 9999
        shrineShop.buy("residual_magnet")
        harness.assert_equal(1, shrine.magnetBase(), "magnet base 1")
        local d0 = shrine.fireDuration()
        shrineShop.buy("dragon_stomach")
        harness.assert_almost_equal(d0 + 1.0, shrine.fireDuration(), 0.001, "+1s dragon 1")
    end)
end)
