local harness = require("tests.test_harness")
local persistence = require("systems.persistence")
local codex = require("systems.codex")
local codexUI = require("systems.codexUI")
local function reset_env()
    love.filesystem.__clearVFS()
    persistence.profilesData = {version = 3, schema_version = 3, activeProfileIndex = nil, profiles = {}}
    persistence.createProfile("CodexHero")
end
harness.describe("Codex: catalogo y registro", function()
    harness.before_each(reset_env)
    harness.it("define 9 entradas y 8 sinergias", function()
        harness.assert_equal(9, #codex.BESTIARY, "bestiario 9")
        harness.assert_equal(8, #codex.SYNERGIES, "sinergias 8")
    end)
    harness.it("seeEnemy registra una vez", function()
        harness.assert_true(codex.seeEnemy("chaser"), "primera vez")
        harness.assert_false(codex.seeEnemy("chaser"), "duplicado no")
        harness.assert_false(codex.seeEnemy(42), "tipo invalido no")
        local e = persistence.getActiveProfile().codex.enemiesSeen
        harness.assert_true(e.chaser, "persistido")
    end)
    harness.it("seeMiniBoss mapea etapa a id", function()
        harness.assert_true(codex.seeMiniBoss(1), "etapa 1")
        harness.assert_false(codex.seeMiniBoss(1), "duplicado no")
        local m = persistence.getActiveProfile().codex.miniBossesSeen
        harness.assert_true(m.wall_crusher, "triturador visto")
        harness.assert_true(codex.seeMiniBoss(99), "etapa clamp a 5")
    end)
    harness.it("checkSynergies detecta pares del inventario", function()
        local shop = {inventory = {shield = true, bomb = true}, slots = {}}
        local found = codex.checkSynergies(shop)
        harness.assert_equal(1, #found, "1 sinergia")
        harness.assert_equal("reactive_shield", found[1], "escudo reactivo")
        local again = codex.checkSynergies(shop)
        harness.assert_equal(0, #again, "ya conocida no repite")
        local none = codex.checkSynergies({inventory = {}, slots = {}})
        harness.assert_equal(0, #none, "sin items nada")
    end)
    harness.it("counts resume el progreso", function()
        codex.seeEnemy("patroller")
        codex.seeMiniBoss(3)
        local e, m, s = codex.counts()
        harness.assert_equal(1, e, "1 enemigo")
        harness.assert_equal(1, m, "1 mini")
        harness.assert_equal(0, s, "0 sinergias")
    end)
    harness.it("syncCodex persiste", function()
        codex.seeEnemy("spawner")
        harness.assert_true(persistence.syncCodex(), "sync ok")
    end)
    harness.it("codexUI dibuja sin errores", function()
        local mod = {buttonRects = {}, panelPad = 12, panelX = 10, panelY = 10, panelW = 400, panelH = 500}
        local ok, err = pcall(function() codexUI.draw(mod) end)
        harness.assert_true(ok, "draw ok: " .. tostring(err))
        harness.assert_equal(1, #mod.buttonRects, "boton cerrar")
        harness.assert_equal("close_codex", mod.buttonRects[1].action, "accion cerrar")
    end)
end)
