local harness = require("tests.test_harness")
local modes = require("systems.modes")
local world = require("core.world")
local function reset_env()
    world.state.modo = "estandar"
    world.state.timeLimit = nil
    world.state.timeUp = nil
    world.state.scoreMultiplier = 1
    world.state.runNoBomb = nil
    world.state.runNoShield = nil
end
harness.describe("Modes: desbloqueos GDD", function()
    harness.before_each(reset_env)
    harness.it("estandar siempre abierto", function()
        harness.assert_true(modes.isUnlocked("estandar", nil), "sin perfil")
    end)
    harness.it("endless exige vencer E5", function()
        harness.assert_false(modes.isUnlocked("endless", {stats = {highestStage = 5}}), "E5 sin flag")
        harness.assert_true(modes.isUnlocked("endless", {stats = {endlessUnlocked = true}}), "flag E5")
    end)
    harness.it("rush exige record 3000", function()
        harness.assert_false(modes.isUnlocked("rush", {highScore = 2999, stats = {}}), "2999 no")
        harness.assert_true(modes.isUnlocked("rush", {highScore = 3000, stats = {}}), "3000 si")
    end)
    harness.it("pacifista exige etapa 3", function()
        harness.assert_false(modes.isUnlocked("pacifista", {stats = {highestStage = 2}}), "E2 no")
        harness.assert_true(modes.isUnlocked("pacifista", {stats = {highestStage = 3}}), "E3 si")
        harness.assert_true(modes.isUnlocked("pacifista", {achievements = {stage_3 = true}, stats = {}}), "logro si")
    end)
end)
harness.describe("Modes: arranque y rush", function()
    harness.before_each(reset_env)
    harness.it("applyOnStart configura rush 180s x3", function()
        world.state.modo = "rush"
        modes.applyOnStart(world.state)
        harness.assert_equal(180, world.state.timeLimit, "limite 180")
        harness.assert_equal(3, world.state.scoreMultiplier, "x3")
    end)
    harness.it("applyOnStart estandar sin limite", function()
        modes.applyOnStart(world.state)
        harness.assert_nil(world.state.timeLimit, "sin limite")
        harness.assert_equal(1, world.state.scoreMultiplier, "x1")
    end)
    harness.it("updateRush descuenta y agota una vez", function()
        world.state.modo = "rush"
        world.state.timeLimit = 0.05
        harness.assert_false(modes.updateRush(0.01), "aun no")
        harness.assert_true(modes.updateRush(0.1), "agota")
        harness.assert_true(world.state.timeUp, "flag timeUp")
        harness.assert_equal(0, world.state.timeLimit, "clamp 0")
    end)
    harness.it("scaleStage crece desde etapa 6", function()
        local m6 = modes.scaleStage(6)
        local m9 = modes.scaleStage(9)
        harness.assert_true(m9.targetMult > m6.targetMult, "objetivo crece")
        harness.assert_true(m9.spawnRate > m6.spawnRate, "spawn crece")
        harness.assert_equal("vacio", m6.biome, "bioma vacio")
    end)
end)
