local harness = require("tests.test_harness")
local persistence = require("systems.persistence")
local bounty = require("systems.bounty")
local world = require("core.world")
local achievementsMod = require("systems.achievements")
local function reset_env()
    love.filesystem.__clearVFS()
    persistence.profilesData = {version = 3, schema_version = 3, activeProfileIndex = nil, profiles = {}}
    persistence.createProfile("BountyHero")
    world.state.monedas = 0
    world.state.highScore = 0
    world.state.highestStreak = 1.0
    world.state.player = {body = {{x = 5, y = 5}, {x = 4, y = 5}, {x = 3, y = 5}}}
    world.set("bounties", {active = {}, furiosoStreak = 0, constrictorKills = 0})
end
harness.describe("Bounty: roll y progreso", function()
    harness.before_each(reset_env)
    harness.it("roll genera 2 contratos activos con targets", function()
        local active = bounty.roll()
        harness.assert_equal(2, #active, "2 contratos por run")
        harness.assert_equal("cerco_maestro", active[1].id, "primero cerco")
        harness.assert_equal(4, active[1].target, "target cerco 4")
        harness.assert_equal("rapido_furioso", active[2].id, "segundo furioso")
    end)
    harness.it("cerco completa con 4 kills y paga 30", function()
        bounty.roll()
        harness.assert_false(bounty.progress("cerco_maestro", 2), "2/4 no completa")
        harness.assert_true(bounty.progress("cerco_maestro", 2), "4/4 completa")
        harness.assert_equal(30, world.state.monedas, "paga 30$")
        harness.assert_true(bounty.find("cerco_maestro").done, "marcado done")
        harness.assert_false(bounty.progress("cerco_maestro", 1), "completado no repite")
    end)
    harness.it("furioso paga 40 y otorga cofre escudo", function()
        bounty.roll()
        local okShop, shop = pcall(require, "systems.shop")
        if okShop and shop then shop.shieldActive = false end
        harness.assert_true(bounty.progress("rapido_furioso", 3), "3/3 completa")
        harness.assert_equal(40, world.state.monedas, "paga 40$")
        if okShop and shop then harness.assert_true(shop.shieldActive, "cofre escudo") end
    end)
    harness.it("pacifista paga 50", function()
        bounty.roll({{id = "pacifista_tactico", reward = 50}})
        harness.assert_true(bounty.progress("pacifista_tactico", 1), "1/1 completa")
        harness.assert_equal(50, world.state.monedas, "paga 50$")
    end)
    harness.it("archive mueve done a historial y limpia", function()
        bounty.roll()
        bounty.progress("cerco_maestro", 4)
        local n = bounty.archive()
        harness.assert_equal(1, n, "archiva 1")
        local p = persistence.getActiveProfile()
        harness.assert_equal(1, #p.bounties.history, "historial con 1")
        harness.assert_equal("cerco_maestro", p.bounties.history[1].id, "id correcto")
        harness.assert_equal(0, #bounty.active(), "activos limpios")
    end)
    harness.it("syncBounties persiste historial", function()
        harness.assert_true(persistence.syncBounties({{id = "x", at = 1}}), "sync ok")
        harness.assert_equal(1, #persistence.getActiveProfile().bounties.history, "historial sync")
    end)
    harness.it("payload source no rompe achievements", function()
        local ok, err = pcall(function()
            achievementsMod.check("enemyKilled", {source = "constrictor"})
        end)
        harness.assert_true(ok, "check tolera payload: " .. tostring(err))
    end)
    harness.it("progreso en contrato inexistente es falso", function()
        bounty.roll()
        harness.assert_false(bounty.progress("inexistente", 1), "id desconocido")
    end)
end)
